"""
SQL guardrail for the NLQ agent. Validates SQL generated by the agent
before it is executed against the database.

Expected usage:
    from guardrails.sql_guardrail import check_sql

    result = check_sql("SELECT revenue FROM sales", datasource="GenericERP")
    if not result["allowed"]:
        raise ValueError(result["reason"])
"""

import json
import os
import re


# ---------------------------------------------------------------------------
# Compiled patterns
# ---------------------------------------------------------------------------

# Keywords that must never appear anywhere in the SQL, including subqueries
# and writable CTEs (PostgreSQL supports INSERT/UPDATE/DELETE inside CTEs)
_DESTRUCTIVE_CLAUSE_RE = re.compile(
    r"\b(DROP|TRUNCATE|DELETE|ALTER|INSERT|UPDATE|EXEC(?:UTE)?|MERGE|CALL)\b",
    re.IGNORECASE,
)

# SQL comment syntax used for injection
_COMMENT_RE = re.compile(r"(--|/\*|\*/)")

# UNION used to smuggle a second query after a legitimate one
_UNION_RE = re.compile(r"\bUNION\b", re.IGNORECASE)

# Table references after FROM or JOIN — skips subqueries that start with (
_TABLE_REF_RE = re.compile(
    r"\b(?:FROM|JOIN)\s+(?!\()"
    r"([A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*)",
    re.IGNORECASE,
)

# CTE alias names — these are not real tables and must be excluded from
# the allowlist check (matches both the first CTE and subsequent ones)
_CTE_NAME_RE = re.compile(
    r"(?:WITH|,)\s+([A-Za-z_]\w*)\s+AS\s*\(",
    re.IGNORECASE,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _first_keyword(sql: str) -> str | None:
    """Return the first SQL keyword token, uppercased, or None if unparseable."""
    m = re.match(r"\s*([A-Za-z_]\w*)", sql)
    return m.group(1).upper() if m else None


def _extract_table_names(sql: str) -> set[str]:
    """
    Extract every table name referenced in FROM and JOIN clauses.
    Skips subqueries (which begin with a parenthesis) and strips schema
    prefixes so that 'dbo.customers' is recorded as 'customers'.
    """
    tables: set[str] = set()
    for m in _TABLE_REF_RE.finditer(sql):
        bare = m.group(1).split(".")[-1].lower()   # strip optional schema prefix
        tables.add(bare)
    return tables


def _extract_cte_names(sql: str) -> set[str]:
    """
    Return the set of CTE alias names defined in WITH clauses. These are
    virtual tables and must not be validated against the table allowlist.
    """
    return {name.lower() for name in _CTE_NAME_RE.findall(sql)}


def _load_allowed_tables(allowlist_path: str, datasource: str) -> list[str] | None:
    """
    Load the allowed_tables list for *datasource* from the allowlist config.
    Returns None if the file is missing or the datasource is not registered.
    """
    if not os.path.isfile(allowlist_path):
        return None
    with open(allowlist_path, encoding="utf-8") as fh:
        config = json.load(fh)
    for entry in config.get("datasources", []):
        if entry.get("name", "").lower() == datasource.lower():
            return [t.lower() for t in entry.get("allowed_tables", [])]
    return None


# ---------------------------------------------------------------------------
# Individual checks
# ---------------------------------------------------------------------------

def _check_statement_type(sql: str) -> dict:
    """
    Enforce that the statement is a read-only query. Only SELECT and WITH
    (used to introduce CTEs before a SELECT) are permitted as the leading
    keyword. INSERT, UPDATE, DELETE, DROP, TRUNCATE, ALTER, EXEC, and all
    other DML/DDL verbs are rejected immediately.
    """
    keyword = _first_keyword(sql)
    if keyword is None:
        return {"allowed": False, "reason": "Blocked: SQL is empty or could not be parsed."}
    if keyword not in ("SELECT", "WITH"):
        return {
            "allowed": False,
            "reason": (
                f"Blocked: only SELECT statements are permitted; "
                f"statement begins with '{keyword}'."
            ),
        }
    return {"allowed": True}


def _check_destructive_clauses(sql: str) -> dict:
    """
    Scan the entire SQL string — including subqueries, CTEs, and string
    literals — for destructive keywords that must never appear regardless
    of query depth. This catches writable CTEs (e.g. WITH x AS (DELETE …))
    and correlated subqueries that embed DML inside an otherwise valid SELECT.
    Blocked keywords: DROP, TRUNCATE, DELETE, ALTER, INSERT, UPDATE, EXEC,
    MERGE, CALL.
    """
    m = _DESTRUCTIVE_CLAUSE_RE.search(sql)
    if m:
        return {
            "allowed": False,
            "reason": (
                f"Blocked: destructive keyword '{m.group(1).upper()}' "
                f"is not permitted anywhere in the SQL."
            ),
        }
    return {"allowed": True}


def _check_comment_injection(sql: str) -> dict:
    """
    Reject SQL that contains comment syntax (-- or /* */). Comments are a
    common injection vector used to truncate a query mid-statement, bypass
    keyword checks, or hide malicious clauses from casual inspection.
    Legitimate NLQ-generated SQL should never require comments.
    """
    m = _COMMENT_RE.search(sql)
    if m:
        token = m.group(1)
        style = "block comment (/* */)" if token in ("/*", "*/") else "line comment (--)"
        return {
            "allowed": False,
            "reason": f"Blocked: SQL comment syntax detected ({style}); comments are not permitted.",
        }
    return {"allowed": True}


def _check_union_injection(sql: str) -> dict:
    """
    Block UNION-based injection. Attackers append a second SELECT via UNION
    to exfiltrate data from tables not intended for the original query. Since
    the NLQ agent is not expected to produce UNION queries for normal business
    questions, any occurrence of UNION is treated as a potential injection.
    """
    if _UNION_RE.search(sql):
        return {
            "allowed": False,
            "reason": "Blocked: UNION keyword detected; UNION-based injection is not permitted.",
        }
    return {"allowed": True}


def _check_table_allowlist(sql: str, datasource: str, allowlist_path: str) -> dict:
    """
    Verify that every table referenced in the SQL is explicitly listed in the
    allowlist for the specified datasource. Loads 'allowed_tables' from
    allowlist_config.json, identifies real tables (excluding CTE aliases), and
    rejects any table not on the list. Fails closed if the allowlist file is
    missing or the datasource is not registered — the query is blocked rather
    than allowed through unvalidated.
    """
    allowed = _load_allowed_tables(allowlist_path, datasource)

    if allowed is None:
        return {
            "allowed": False,
            "reason": (
                f"Blocked: datasource '{datasource}' was not found in the allowlist "
                f"config at '{allowlist_path}'. Register the datasource before querying."
            ),
        }

    referenced = _extract_table_names(sql)
    cte_aliases = _extract_cte_names(sql)
    real_tables = referenced - cte_aliases

    disallowed = sorted(t for t in real_tables if t not in allowed)
    if disallowed:
        return {
            "allowed": False,
            "reason": (
                f"Blocked: SQL references table(s) not in the allowlist for "
                f"datasource '{datasource}': {', '.join(disallowed)}."
            ),
        }

    return {"allowed": True}


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def check_sql(
    sql: str,
    datasource: str,
    allowlist_path: str = "config/allowlist_config.json",
) -> dict:
    """
    Validate SQL produced by the NLQ agent before it is executed.

    Runs five checks in order:
      1. Statement type    — only SELECT / WITH … SELECT are permitted
      2. Destructive clauses — DROP, DELETE, TRUNCATE, etc. blocked everywhere
      3. Comment injection  — -- and /* */ syntax rejected
      4. UNION injection    — UNION keyword rejected
      5. Table allowlist   — every referenced table must be registered for
                              the given datasource in allowlist_config.json

    Args:
        sql:            The SQL string to validate.
        datasource:     Name of the datasource (must match an entry in the
                        allowlist config, case-insensitive).
        allowlist_path: Path to allowlist_config.json (default suits a repo-
                        root working directory).

    Returns:
        ``{"allowed": True}`` if all checks pass, or
        ``{"allowed": False, "reason": "<explanation>"}`` on the first failure.
    """
    if not isinstance(sql, str) or not sql.strip():
        return {"allowed": False, "reason": "Blocked: SQL must be a non-empty string."}

    for check in (
        _check_statement_type,
        _check_destructive_clauses,
        _check_comment_injection,
        _check_union_injection,
    ):
        result = check(sql)
        if not result["allowed"]:
            return result

    return _check_table_allowlist(sql, datasource, allowlist_path)
